export const personalInfo = {
  name: "Jarif Ahmed Soumik",
  location: "Dhaka, Bangladesh",
  email: "jasoumik@gmail.com",
  phone: "+8801716684803",
  github: "https://github.com/jasoumik",
  linkedin: "https://linkedin.com/in/jasoumik",
  profilePicture: "/profile.jpg",
  heroDescription:
  "From the beginning, I have been very passionate about Software Development (Full-Stack). Also, I have been started working professionally since 2020. I always hope to enter into a software company where I can utilize my skills and knowledge in a better working environment and I want to give meaningful output to the company with my ability."
};

export const workExperience = [
  {
    company: "Blubird Interactive Limited",
    location: "Dhaka, Bangladesh",
    position: "Software Engineer (Backend)",
    period: "January 2023 - Present",
    achievements: [
      "Full Development and Support on Moving Manager Application.",
      "Contributed to every projects of Blubird.",
      "Completed many RnDs when needed.",
      "Managed full team of Moving Manager.",
    ],
  },
  {
    company: "BRAC IT Services Limited",
    location: "Dhaka, Bangladesh",
    position: "Software Engineer | Financial Services",
    period: "May 2021 - December 2022",
    achievements: [
      "Worked on BRAC-Payroll.",
      "Contributed to BRAC IT Official Website.",
      "Completed an agent banking module for BBL.",
      "Full development using Symfony Framework.",
      "Worked with many new tools from scratch.",
    ],
  },
  {
    company: "BRAC IT Services Limited",
    location: "Dhaka, Bangladesh",
    position: "Software Engineer Intern",
    period: "Feb 2021 - April 2021",
    achievements: [
      "Worked with the ERP System of BRAC.",
      "Learned under guidance of skilled and experienced technical leads.",
      "Hands-on learning and development with Symfony Framework.",
      "Worked with many new tools from scratch.",
    ],
  },
  {
    company: "Antopolis",
    location: "Dhaka, Bangladesh",
    position: "Backend Developer Intern (Laravel)",
    period: "September 2020 - November 2020",
    achievements: [
      "Successfully completed 2 projects from scratch.",
      "Learned new technologies and implemented them effectively.",
      "Always delivered expected outputs on time.",
    ],
  },
  {
    company: "BRAC IT Services & Fast Track Future Leader",
    location: "Dhaka, Bangladesh",
    position: "PHP Trainee",
    period: "October 2020 - January 2021",
    achievements: [
      "Learned more about software engineering fundamentals.",
      "Team organizing and leadership experience.",
      "Organized feedback sessions and improved communication skills.",
    ],
  },
];


export const education = [
  {
    institution: "BRAC University",
    location: "Dhaka, Bangladesh",
    degree: "Bachelor of Science (B.Sc.) in Computer Science",
    period: "2016 - 2020",
    achievements: [],
  },
  {
    institution: "Rajuk Uttara Model College",
    location: "Dhaka, Bangladesh",
    degree: "Higher Secondary School Certificate (Science)",
    period: "2013 - 2015",
    achievements: [],
  },
  {
    institution: "Armed Police Battalion Public School & College",
    location: "Bogura, Bangladesh",
    degree: "Secondary School Certificate (Science)",
    period: "2011 - 2013",
    achievements: [],
  },
];

export const skills = {
  programmingLanguages: [
    "PHP (8.4 - 7.2)",
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "Java (Basics)",
    "Python (Basics)",
    "C++ (Basics)",
  ],
  frontendDevelopment: [
    "React",
    "Bootstrap",
    "Tailwind CSS",
    "jQuery",
    "Ag-Grid",
    "ChartJS",
    "AlpineJS",
    "DataTables",
  ],
  backendDevelopment: [
    "Symfony (5.4 & 4.4)",
    "Laravel (12 - 6)",
    "Drupal 9",
    "RESTful API",
    "OAuth2.0",
    "JWT Authentication",
    "Xdebug 3.0",
  ],
  databaseAndStorage: [
    "MySQL",
    "PostgreSQL",
    "Oracle",
    "SQLite",
    "Doctrine ORM",
    "Eloquent ORM",
  ],
  cloudAndDevOps: [
    "Docker (Beginner)",
    "Cloud Computing",
    "OpenStack SAIO",
    "C-Panel",
    "Oracle VM",
    "CI/CD with GitHub/GitLab Actions",
  ],
  toolsAndServices: [
    "Composer",
    "Postman",
    "Git (GitHub, GitLab, BitBucket)",
    "IntelliJ IDEA",
    "PHPStorm",
    "VS Code",
    "NetBeans",
    "Dr. Java",
    "Codeblocks",
    "CodeCeption",
    "PHPUnit",
    "MS Word",
    "MS Excel",
    "MS PowerPoint",
    "WordPress",
  ],
};

export const projects = [
  {
    title: "Moving Manager",
    github: "https://github.com/kazi-shahin/mm",
    description: [
      "A comprehensive web application for managing moving and relocation services.",
      "Includes customer management, job tracking, invoicing, and payments.",
      "Built with Laravel and React for a seamless full-stack experience.",
      "Implements advanced filtering, search, and reporting features.",
      "Designed for scalability and real-world business use cases.",
    ],
  },
  {
    title: "IntoPocket",
    github: "https://github.com/jasoumik/intopocket",
    description: [
      "A personal finance management tool to track income, expenses, and savings.",
      "Offers insights into financial habits with charts and summaries.",
      "Developed using Laravel + React with Sanctum authentication.",
      "Responsive design with Tailwind CSS and modern UI components.",
      "Deployed and accessible at https://intopocket.intovah.com/.",
    ],
  },
  {
    title: "IntoStock",
    github: "https://github.com/jasoumik/intostock",
    description: [
      "An inventory management system for businesses to manage stock and products.",
      "Supports categories, product listings, and invoice management.",
      "Built with Laravel and React for robust backend and dynamic frontend.",
      "Implements role-based access and secure authentication.",
      "Lightweight, scalable, and optimized for small-to-medium businesses.",
    ],
  },
];

export const awards = [
  {
    name: "Interactivity with JavaScript",
    issuer: "Coursera",
    date: "",
    type: "Certification",
    credentialId: "UMSEDPC5R427",
  },
  {
    name: "Code with HTML, CSS, and JavaScript",
    issuer: "Coursera",
    date: "",
    type: "Certification",
    credentialId: "GZ43AUPAWPP8",
  },
  {
    name: "Building Web Applications in PHP",
    issuer: "Coursera",
    date: "",
    type: "Certification",
    credentialId: "DHRALXGZRT93",
  },
  {
    name: "Introduction to Structured Query Language (SQL)",
    issuer: "Coursera",
    date: "",
    type: "Certification",
    credentialId: "7EYD7YU8R5CK",
  },
  {
    name: "Programming for Everybody (Getting Started with Python)",
    issuer: "Coursera",
    date: "",
    type: "Certification",
    credentialId: "C5WYL26MUUS9",
  },
  {
    name: "Building Database Applications in PHP",
    issuer: "Coursera",
    date: "",
    type: "Certification",
    credentialId: "RVM62RWSKQF4",
  },
  {
    name: "JavaScript, jQuery, and JSON",
    issuer: "Coursera",
    date: "",
    type: "Certification",
    credentialId: "Z6ZSHQEKYRP",
  },
  {
    name: "MS Excel Basics for Beginners",
    issuer: "Bohubrihi",
    date: "",
    type: "Certification",
    credentialId: "14027-158-990-4547",
  },

  // Recommended courses from biTS-FTFL / BCC
  {
    name: "Oral Communication for Engineering Leaders",
    issuer: "Coursera",
    date: "",
    type: "Recommended Course",
    credentialId: "QZGCBU9JVAJV",
  },
  {
    name: "Giving Helpful Feedback",
    issuer: "Coursera",
    date: "",
    type: "Recommended Course",
    credentialId: "XK2QGDKRC8R2",
  },
  {
    name: "IS/IT Governance",
    issuer: "Coursera",
    date: "",
    type: "Recommended Course",
    credentialId: "TJYLK5AD9KGK",
  },
  {
    name: "Effective Problem-Solving and Decision-Making",
    issuer: "Coursera",
    date: "",
    type: "Recommended Course",
    credentialId: "MDWQZQRC6W2H",
  },
  {
    name: "Creative Problem Solving",
    issuer: "Coursera",
    date: "",
    type: "Recommended Course",
    credentialId: "6PEXSGCB5HB9",
  },
  {
    name: "Understanding User Needs",
    issuer: "Coursera",
    date: "",
    type: "Recommended Course",
    credentialId: "G67RQNRZQMDC",
  },
  {
    name: "The Science of Well-Being",
    issuer: "Coursera",
    date: "",
    type: "Recommended Course",
    credentialId: "8BDULRTZJMQE",
  },
  {
    name: "Teamwork Skills: Communicating Effectively in Groups",
    issuer: "Coursera",
    date: "",
    type: "Recommended Course",
    credentialId: "TQA2C3HKNJ29",
  },
  {
    name: "Version Control with Git",
    issuer: "Coursera",
    date: "",
    type: "Recommended Course",
    credentialId: "5X9TCVRTQDZE",
  },
  {
    name: "Object-Oriented Design",
    issuer: "Coursera",
    date: "",
    type: "Recommended Course",
    credentialId: "M5WW5YPKSJMR",
  },
  {
    name: "Client Needs and Software Requirements",
    issuer: "Coursera",
    date: "",
    type: "Recommended Course",
    credentialId: "PSV3KYKH8E8F",
  },
  {
    name: "Software Processes and Agile Practices",
    issuer: "Coursera",
    date: "",
    type: "Recommended Course",
    credentialId: "ZT2GMM8BF2KT",
  },
  {
    name: "Work Smarter, Not Harder: Time Management for Personal & Professional Productivity",
    issuer: "Coursera",
    date: "",
    type: "Recommended Course",
    credentialId: "D5G2H86CXXAJ",
  },
];

